Repository jelhan/ember-cli-browser-navigation-button-test-helpers, pull requests merged in 2022-02, with the labels that each got.

#34 run CI using GitHub Actions
  .github/workflows/ci.yml
  config/ember-try.js
  package.json
  yarn.lock
Labels: enhancement

#33 Remove ember-router-service-polyfill
  package.json
  yarn.lock
Labels: enhancement

#39 setup release-it to partly automate releases
  CHANGELOG.md
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#42 upgrade Ember CLI to 3.12
  package.json
  testem.js
  tests/dummy/config/ember-cli-update.json
  yarn.lock
Labels: internal

#67 run Ember 3.28 scenario in CI
  .github/workflows/ci.yml
Labels: internal

#69 drop support for node 8 and 10
  README.md
  package.json
Labels: breaking

#70 drop support for Ember < 3.20
  .github/workflows/ci.yml
  README.md
  config/ember-try.js
Labels: breaking

#81 Support Ember v4
  .github/workflows/ci.yml
Labels: enhancement
